version: "3.7"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" # default mqtt port
      - "9001:9001" # default mqtt port for websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"

volumes:
  config:
  data:
  log:

networks:
  db_backend:
    driver: bridge
  default:
    name: mqtt-network
